### ISSUE TITLE
Better Issue Tracking

### ISSUE THREAD

**Issue by scottgonzalez** [jquery/content#4]
@agcolom requested that I open a single issue with all requests.
- [ ] Make the tracking code public
- [ ] Monitor all repositories
- [ ] Track pull requests and issues
- [ ] Track opens and closes, not just total open count
- [ ] Track average age
- [ ] Push the data into Splunk

**Comment by vpowerrc** [comment]
Hi,
I would like to contribute to this project via GSoC this year. Is there a mentor who can I discuss it with?

Regards,
Viduranga

**Comment by agcolom** [comment]
@vpowerrc you can discuss this with me.

**Comment by vpowerrc** [comment]
To to this we need to use the Github API, which means we need to use a back-end language as well.

But In the ideas page the programming language for back-end wasn't mentioned. Can we use any language?

**Comment by arthurvr** [comment]
> But In the ideas page the programming language for back-end wasn't mentioned. Can we use any language?

All our tooling is written in Node atm, I would prefer to stay doing so.

**Comment by arschmitz** [comment]
+1 for node. Other then a very small bit of php mobile demos, core tests, and for our websites ( we use wordpress ) we use nothing but node/js I would like to see us stick with node. We also actually have an issue on core to remove the php dependency and switch to node also https://github.com/jquery/jquery/issues/1999 . JavaScript is what all of our contributors are familiar with and I think would prefer to have to maintain.

**Comment by vpowerrc** [comment]
Cool!
I looked to Github API. They also supports webhooks.
Is this application going to depend on api calls only or should we maintain a database to store data from Github as well?
I'm still trying to get my mind around the basic architecture of the application. Sorry for any inconvenience caused.

**Comment by agcolom** [comment]
I'm thinking that it would be a good idea to store the data as well. I'd like views from @scottgonzalez @gnarf @arschmitz regarding this.

**Comment by scottgonzalez** [comment]
Using webhooks provides us with realtime data, but also makes it harder to recover from any downtime. If you don't know what you missed, there's no easy way to just grab the missing data.

Using API calls, we can get all the changes since the last time we fetched. As for how often we should fetch data, that I'm not sure about since we don't yet know how many requests that will result in.

**Comment by scottgonzalez** [comment]
It's also worth mentioning other tools.

[Metrics Grimoire](http://metricsgrimoire.github.io/) is open source and powers the data portion of Bitergia's dashboards (see http://demo.bitergia.com/browser/). However, it's GPL and written in python, so we may not want to even look into it.

jQuery Foundation uses Splunk to store tons of data, but we don't have any of that open to the public right now. While I originally pushed for this data to just go into Splunk since that would provide all the graphing and analysis for us, it would also be nice to have a standalone product that others can use.

**Comment by vpowerrc** [comment]
@scottgonzalez 
Yes it depends on the requirements of the application. If the app doesn't have to updated real time best thing is to use API calls. Then we can use a cron job to fetch data and update the database at a given interval.

@agcolom 
I would like to work on designing the database structure. But there are some requirements I don't quite understand. Can you guys help me with them?
Here are them:
*Make the tracking code public 
*Monitor all repositories - What do you mean by monitoring. What are the specifics?
*Track age range (as well as average age)
*View tracking by team (i.e. all repos that fall under the chosen team) - Teams should be assigned by the application itself, right? since there there is no such thing as team in Github.
*Push the data into Splunk - @scottgonzalez said that he already push them to Splunk. Should I improve it?

Initial DB structure:
*teams
*repositories
*users
*pull requests
*issues 

Please add your comments.

**Comment by scottgonzalez** [comment]
> *Make the tracking code public 

It must live in a public repository. The current tracking code only exists on a private server.

> *Monitor all repositories - What do you mean by monitoring. What are the specifics?

Monitoring = tracking. It's everything that this task is about. I'm not sure what else to say here, it should track every public repository in the jquery org.

> *Track age range (as well as average age)

Track how long issues and PRs have been open.

> *View tracking by team (i.e. all repos that fall under the chosen team) - Teams should be assigned by the application itself, right? since there there is no such thing as team in Github.

Well, there are teams in GitHub, but I'm not sure what @agcolom had in mind.

> *Push the data into Splunk - @scottgonzalez said that he already push them to Splunk. Should I improve it?

When did I say that? If that were done, this project would be half-done.

**Comment by scottgonzalez** [comment]
> Initial DB structure:
> *teams
> *repositories
> *users
> *pull requests
> *issues

It's hard to comment on just a list of table names.

**Comment by arschmitz** [comment]
For a database for this since we will probably pull JSON data it might make sense to use a JSON document based database like couchbase or couchdb. I actually talked to someone from couchbase earlier this week about something unrelated, and they seemed interested in working with us.

**Comment by scottgonzalez** [comment]
I'm not sure how the source data being JSON has anything to do with the data format for the database. The type of database we use should be based on the data we're storing and how we're using that data.

**Comment by vpowerrc** [comment]
@scottgonzalez
Sorry, I have misunderstood your statement regarding pushing data into Spluck.
I haven't use Spluck before. I hope that won't be problem to pursue this project.
Am I just to send the data grabbed by Github via API calls or do I need to do some processing before sending them to Splunk?

>It's hard to comment on just a list of table names.
I'm not talking about the relationships between tables. But it looks like, these are the basic tables we are going to need to store the data. Am I wrong?

**Comment by scottgonzalez** [comment]
> Am I just to send the data grabbed by Github via API calls or do I need to do some processing before sending them to Splunk?

You would have to process the data into a format that Splunk can understand. However, as I said, we may not use Splunk. This is something that needs to be determined.

> I'm not talking about the relationships between tables. But it looks like, these are the basic tables we are going to need to store the data. Am I wrong?

Again, without any details that's not a question that can really be answered.

**Comment by vpowerrc** [comment]
>Again, without any details that's not a question that can really be answered.

Would an ER diagram suffice?

**Comment by scottgonzalez** [comment]
> Would an ER diagram suffice?

Sure, or just actually providing details about the tables.

**Comment by sudheesh001** [comment]
@scottgonzalez @agcolom 

I am interested in this project too and would like to work on it. Could you explain a little more about what you mean by `Making the tracking code public` ?
```
Monitor all repositories
Track pull requests and issues
Track opens and closes and not just an open total count
```
I think using a cron would be a good way to keep track of these, probably scan the jquery/* github repos every 2 minutes for finding out changes if any ? In case the state of a particular issue / PR has changed, a hook which triggers the corresponding operations. At Mozilla, There's [autolander](https://github.com/mozilla/autolander), it checks for PR's or changes in PRs and triggers the required CI services or the bugzilla services accordingly. It'd be nice to have a look at it since it's built in JavaScript too.

On the application database, we can manage the other content like tracking the age ranges, its averages, the Percentage of the PR's can directly be obtained from the `Open` and `Closed` statuses of the PR's per repository.

Waffle.io seems like a very good existing option to learn from to customize the visualisations and tracking dashboard as required by jquery. I believe that using an ORM like [Sequelize](http://docs.sequelizejs.com/en/latest/) would simplify the work and not cause much of an issue with changing database schemas and in its migrations, rather than having to migrate the new schema from the SQL file every time an unexpected change occurs to it. Going with a MySQL database with Sequelize as the ORM would be a great step towards building this application.

When it comes to the front end, is there a necessity to use a front end framework like AngularJS ? or Can it be done in plain HTML/JS/CSS

As an addon, it'd be great to have analytics of contributors, their lines of codes, commits etc.., and gamify onto a leaderboard. There could also be an option for showing stats like
- What time of the day do contributors generally commit their code.
- How many timezones & countries/places are contributors from.

A few things that should be considered is the API Query limit that'd be allowed. Would it be better if we used the [Github Archive](https://www.githubarchive.org/) instead ? They have a [Big Query System](https://github.com/blog/1112-data-at-github) too, maybe that'd be of help too.

This seems like a really exciting project and I would love to contribute to this.

**Comment by vpowerrc** [comment]
@scottgonzalez 
Here's my initial db design.

![Image of Yaktocat]
(http://i.imgur.com/Kozh3ix.png)

**Comment by srk12345** [comment]
Hi,
I would like to contribute to jQuery Learning Center project via GSoC .Is there a mentor who can help me to start the work?
shahrukh

**Comment by arthurvr** [comment]
@agcolom is mentor, @srk12345. We all hang out in Freenode IRC, #jquery-content. Also be sure to read https://github.com/jquery/gsoc/wiki/Getting-started-for-students.

**Comment by srk12345** [comment]
HI @agcolom i would like to contribute to jQuery Learning project. Plz tell me how can i help u in this project.

**Comment by srk12345** [comment]
Hi @agcolom Plz help me regarding jQuery learning center project.

**Comment by jacquerie** [comment]
Hey everyone. I wrote a small CLI tool in Node that satisfies some of the requirements in the [first](https://github.com/jquery/content/issues/4#issue-54246432) [two](https://github.com/jquery/content/issues/4#issuecomment-69899864) comments.

Here's an example of its output:
```JSON
{
  "repo": "jquery/jquery",
  "total": 2124,
  "openPulls": 11,
  "openPullsAge": {
    "min": 129755,
    "avg": 4160999,
    "max": 12516655
  },
  "openIssues": 99,
  "openIssuesAge": {
    "min": 9629,
    "avg": 7970797,
    "max": 13243015
  },
  "closedPulls": 1773,
  "closedPullsAge": {
    "min": 6,
    "avg": 1408170,
    "max": 52149399
  },
  "closedIssues": 241,
  "closedIssuesAge": {
    "min": 6,
    "avg": 1277130,
    "max": 12439871
  }
}
```
where the age of a PR or issue is measured in seconds.

If I understood this task correctly, the desired outcome of this project is some kind of admin tool (dashboard) that allows for easy outlier detection and progress reporting. In a sense, this tool should measure the "health" of a repository: a project has low health if PRs tend to go stale, issues stay open for long, nothing gets done...

For this reason, I don't think the commercial solutions ([Bee](http://www.neat.io/bee/github-issues-client.html), [Waffle](https://waffle.io/), and [HuBoard](https://huboard.com/)) are right for this job, since they mostly deal with assigning/creating issues. Something that comes closer is [GHTorrent's pullreq-perf](http://ghtorrent.org/pullreq-perf/).

Several components are needed to build such a tool.

1. Something that crawls GitHub's API and outputs some simplified form: I'm currently rolling my own using [psunkara/octonode](https://github.com/pksunkara/octonode); @scottgonzalez told me on IRC about [scottgonzalez/github-request](https://github.com/scottgonzalez/github-request) and [scottgonzalez/github-export](https://github.com/scottgonzalez/github-export).
2. Something that schedules the execution of this crawler, or avoids doing it if determines there's no new data to fetch: this looks doable using one of [these](https://www.npmjs.com/search?q=cron), although I have no experience with any of them.
3. Some persistence layer (CouchDB seems widely favored) and some adapter mechanism to store this data in other backends (Splunk, which I'm not familiar with).
4. Finally, the actual dashboard, an Express app built using some kind of [charting](http://www.highcharts.com/)/[drawing](http://d3js.org/) library.

An advantage of this design is that the fourth bullet point could be swapped with something else; something that comes to mind is a tool like [GHTorrent's PRioritizer](http://ghtorrent.org/prioritizer/#/display/jquery/jquery-mobile/7d6f850d55/), or a tool which can be used by first time contributors to find good/needed/easy work to do.

I'd love to hear feedback on my plan.

**Comment by jacquerie** [comment]
And here's the code I was talking about: https://github.com/jacquerie/github-issues.

BTW, @agcolom, it's definitely possible to know which PRs were merged using this endpoint: https://developer.github.com/v3/pulls/#get-if-a-pull-request-has-been-merged. On the other hand, this probably fails when the maintaner chooses to cherry-pick a commit and close the PR. Is this acceptable?

**Comment by agcolom** [comment]
@jacquerie That sounds like a good plan to me. I don't think cherry-picking a comit and closing a PR is something that happens on a regular basis. Thanks also for the link on the Prioritizer. I was not aware of this tool.

**Comment by scottgonzalez** [comment]
> On the other hand, this probably fails when the maintaner chooses to cherry-pick a commit and close the PR.

That describes about 100% of our PRs.

**Comment by scottgonzalez** [comment]
> I don't think cherry-picking a comit and closing a PR is something that happens on a regular basis.

@agcolom That's our standard practice. We always rebase, edit the commit messages to includes references, then merge. That's effectively a cherry-pick. See http://contribute.jquery.org/repo-maintainers-guide/.

**Comment by agcolom** [comment]
ok, sorry, I was thinking old fixes. so that means this solution would not work then?

**Comment by scottgonzalez** [comment]
It just means that we can't track merges.

**Comment by jacquerie** [comment]
@agcolom only partially. Take for instance these two PRs in jQuery UI:

1. https://github.com/jquery/jquery-ui/pull/1469
2. https://github.com/jquery/jquery-ui/pull/1466

As you can see, the first one was merged in such a way that GitHub API is aware of it, while the other one was not. In fact, now we have:
```bash
$ curl -I https://api.github.com/repos/jquery/jquery-ui/pulls/1469/merge
HTTP/1.1 204 No Content
[...]
```
but
```bash
$ curl -I https://api.github.com/repos/jquery/jquery-ui/pulls/1466/merge
HTTP/1.1 404 Not Found
[...]
```
It should be said, though, that most PRs under the jQuery organization tend to fall in the second case.

**Comment by scottgonzalez** [comment]
jquery/jquery-ui#1469 is an anomaly; it was merged without a reference.

**Comment by jacquerie** [comment]
Yes, rather than "partially" the answer is "almost never".

Another strategy is to use the Issue Events: https://developer.github.com/v3/issues/events/#list-events-for-an-issue. We can listen for a `closed` event where the `commit_id` field is not null, as in https://api.github.com/repos/jquery/jquery-ui/issues/1466/events.

This is still not perfect: the closing commit could be completely different than what was originally proposed in the PR, but it looks like it should work in practice.

**Comment by scottgonzalez** [comment]
That can tell us who closed the issue/PR, but not if a PR was merged. For example, https://api.github.com/repos/jquery/jquery-ui/issues/1287/events will show that the PR was closed via https://github.com/jquery/jquery-ui/commit/4b017b414f107ed3c1dafc7601b61cbcd76acf61 but the PR was not merged, it was simply closed as a different solution was merged.

**Comment by PhilippGrulich** [comment]
Hey guys,

I'm also very interested in joining this project. 
I'm currently attending the Hamburg University of Applied Sciences, Germany and pursuing a BS degree in Computer Sciences. 
I have read your discussion and your ideas and I think this could be a really interesting web app.
In my oppinion angularjs as a frontend framework would be a good choice. Is this an option?
I think the node part could be very slim and only crawls github, stores the data to a DB and delivers the data to the clients. So everywhere is just simple JSON.
As the Database I also think, it would be nice to have a document orientated DB like MongoDB or CouchDB, but at the moment i have the most experiences with MongoDB.

I have created a small prototype, just to test the github api, which is very basic and just shows the repositories and some information about the issues and so on. It also don't have an database yet.

Demo : http://jquery.philipp-grulich.de/app/#/
Github: https://github.com/PhilippGrulich/issue-tracking-tool

Greez Philipp

**Comment by agcolom** [comment]
For all those interested in submitting a proposal, please do not forget to submit your proposal at https://www.google-melange.com/gsoc/homepage/google/gsoc2015

**Comment by g31pranjal** [comment]
I am interested in contributing to this project through Gsoc.

Analyzing the problem, I feel that it can be clearly broken into 3 disjoint segments : 
    1. Scrapping data from GitHub and pushing into DB.
    2. Manipulating and Analyzing the raw data to get clear insights.
    3. Presenting the data in user-friendly format.

Now, I have few ideas for each of these sets : 
    1. Scrapping data : This can be done by means of Scheduled tasking with Cron on a Google App Engine or local server (What should be preferred?). The purpose is to flush raw new data from GitHub into the database. The event to flush data will be triggered only if there is some new data in that transaction.
    2. Manipulation and Analyzing : I am planning to set this as separate segment, because : 
                              1. This can be triggered as an event only when it is required(when we have new data to evaluate !) rather than at all requests. 
                              2. More of the functionalities can be added in future without disturbing the other 2 parts.
The purpose is to get useful insights from raw data like : no of open issues, closed issues, avg. age, age range and data for graphical display on Dashboard.
1. Presentation on Dashboard : A simple angular app or rather just bootstrapped HTML/CSS to display the data. 

@scottgonzalez , @agcolom , @arschmitz , please help me with these doubts regarding the flow : 
    1. Is it fine to do this on Google App Engine ? or should I prefer on local node/js server ?
    2. Will it be fine if I use local DB ? 
    3. What is the extent of information to be shown in pull request ?
    4. Will there be some kind of visibility rules based on the teams of each repository ?
    5. Can I research with more measures to provide on Dashboard page ?

**Comment by scottgonzalez** [comment]
> 1. Is it fine to do this on Google App Engine ? or should I prefer on local node/js server ?

Local

> 1. Will it be fine if I use local DB ? 

Local

> 1. What is the extent of information to be shown in pull request ?

I'm not sure what you're asking.

> 1. Will there be some kind of visibility rules based on the teams of each repository ?

No. Everything is public.

> 1. Can I research with more measures to provide on Dashboard page ?

I'm not sure what you're asking.

**Comment by vidurangaw** [comment]
@scottgonzalez
Did you see my database design above? Do you have any comments?

**Comment by g31pranjal** [comment]
i was planning to track issues on github using crontab. The only problem i face is that theres no option for real time tracking as and when the issue is created. Is there a need of real-time updating in this project?

also what should be the first priority : quick update to data or deep Analysis of issues ??

@scottgonzalez @agcolom  insights please..

**Comment by scottgonzalez** [comment]
Real-time tracking is not important.

**Comment by scottgonzalez** [comment]
> Did you see my database design above? Do you have any comments?

I'm not sure what commitments are. I'm not sure what data you're tracking. I'm not sure how you're analyzing the data. There's a large chunk of missing information.

**Comment by gauravparmar** [comment]
Respected mentors,
I am full of enthusiasm to work on it as my project for GSoC 2015 as this project sounds really interesting and suits my interest.

Being a student who is pursuing M.Tech. in Information Technology, I have also been working as a freelance Full Stack Developer and Graphic Designer since last few years and have knowledge about jQuery, JavaScript, Git/Github, HTML/HTML5, CSS/CSS3, Bootstrap, PHP, MySQL, AJAX, Python, Adobe Photoshop etc.
I have interest in Open Source technology and Open Source Community.

You can also check my Linkedin profile at https://www.linkedin.com/in/gauravbparmar

I have practical experience of working on many projects that include device responsive website designing, web development, graphic designing etc.

After understanding this project I have chopped down this project into these major segments according to my understanding-
1. Continuous fetching of data from Github corresponding to jQuery's repositories through some way.
2. Storage of fetched data into a database for future analysis and information retrieval.
3. Scrutinizing data that is stored in the database and separation of required information related to "issues" from it and further separation of this "issues" related information according to teams that manage different official repositories belonging to jQuery on Github.
4. Manipulation of the separated information and generation of statistics through it.
5. Representation of live statistics on the webpage in a user friendly way. Something like a dashboard.

I would like to use this package for designing a device responsive web application that will serve as Tracking System for issues related to jQuery's Github repositories-

jQuery + AJAX + HTML5 + CSS3 + Bootstrap

For graphic designing-

Adobe Photoshop

For back-end I would like to use below package-

PHP + MySQL + Github API, Webhooks, Bicho Tool (https://github.com/MetricsGrimoire/Bicho) or any other tool that does data fetching work for repositories on Github.

I am completely ready for all the website design and development part except one thing where I am getting stuck, that is the way to grab issues related data from Github for jQuery repositories.

As @scottgonzalez has said above that there are some problems using Webhooks so I have searched further and got Bicho that is one of the tools in the MetricsGrimoire toolset (Also mentioned by @scottgonzalez above).

@agcolom, @scottgonzalez and other mentors please tell -
- your views about Bicho Tool.
- is it okay if I use above technology stack?
- if we use API calls then how often shall we have to fetch the data? What should be the time interval to do this process?
- do you know about any other tool that can aid in this process? 
- will this tracking system have all the features that are currently there in huboard (https://huboard.com)?

I think under your guidance and team work, we can surely turn this project idea into reality.

Here are some of my past projects to build your trust on me -
http://gauravparmar.byethost7.com/myplace
http://youthfest.in
http://www.globalharmonyfundraising.org/
http://gauravparmar.byethost7.com/amaroo/
http://www.priceshaved.com
http://gauravparmar.byethost7.com/project3_ui/

Regards
Gaurav Parmar

**Comment by scottgonzalez** [comment]
> your views about Bicho Tool.

Well, Bicho is written in python. We aim for node and PHP, with a very strong preference toward node.

> is it okay if I use above technology stack?

We'd prefer node over PHP. I don't think we'll use webhooks.

For Bootstrap, I assume you're referring only to the CSS portion?

> if we use API calls then how often shall we have to fetch the data? What should be the time interval to do this process?

That's not an important decision up front. We'll figure that out during development.

> do you know about any other tool that can aid in this process?

https://www.npmjs.com/package/github-request
https://github.com/scottgonzalez/github-export (WIP)

> will this tracking system have all the features that are currently there in huboard (https://huboard.com)?

Extremely different. This is in no way a bug tracker/scrum board/kanban board. It's a read-only analysis on issues and PRs.

**Comment by gauravparmar** [comment]
@scottgonzalez : As https://github.com/scottgonzalez/github-export is in progress so do you think https://www.npmjs.com/package/github-request will satisfy all our needs on that matter or we shall have to tweak it to suit our needs?

@arschmitz : I also found you as a mentor for this project on the ideas list page of jQuery. What would you suggest for grabbing "issues" related data from Github so that it can be used in our web application which will make use of it to serve as issue tracking system?

**Comment by gauravparmar** [comment]
I would also like views on this matter from @agcolom.

**Comment by gauravparmar** [comment]
@scottgonzalez : Yes, we can work on Node.js as well instead of PHP. Actually it will be better. 
Great to see that you worked on https://www.npmjs.com/package/github-request

**Comment by scottgonzalez** [comment]
> As https://github.com/scottgonzalez/github-export is in progress so do you think https://www.npmjs.com/package/github-request will satisfy all our needs on that matter or we shall have to tweak it to suit our needs?

github-export is just a tool built on top of github-request to do the exact type of queries you'll want. You won't have to tweak github-request regardless of whether you use github-export.

**Comment by g31pranjal** [comment]
@scottgonzalez : I could not find any team information on GitHub. From where can i get this info ??
I wanted to know more about this feature and what are your expectations from this?

**Comment by scottgonzalez** [comment]
@g31pranjal Please see my [earlier comment](https://github.com/jquery/content/issues/4#issuecomment-77412536).

**Comment by g31pranjal** [comment]
here are teams in jQuery and they look after the certain repositories. Agreed..

<blockquote>but I'm not sure what @agcolom had in mind.</blockquote>

I wanted to know what is required of this feature and how can I incorporate this in my proposal ?
@scottgonzalez : Anything you feel could be regarding this..
@agcolom : please help out with this

**Comment by agcolom** [comment]
Sorry, I'm not in front of a computer right now but my views are totally inline with those of @scottgonzalez

**Comment by g31pranjal** [comment]
@agcolom @scottgonzalez 
can u please review my Gsoc proposal for Tracking jQuery Issues on GitHub
please suggest if any change or addition is required before finalizing...

**Comment by gauravparmar** [comment]
@scottgonzalez , @agcolom and @arschmitz : 
Should I calculate average age of issues/PRs for individual repositories or for all at once or both?

**Comment by agcolom** [comment]
@gauravparmar As a minimum, it should be per repository so that we can measure and compare the health of each repo. In addition, altogether would be good also for comparison purposes.

**Comment by scottgonzalez** [comment]
Let's not focus on anything that spans every project until the features are done for the individual repositories. There's a lot of disjoint across projects and that will only increase over time.

**Comment by gauravparmar** [comment]
@agcolom  , @scottgonzalez and @arschmitz :
- What time unit should be used to show age, average age etc.? Milliseconds, seconds, minutes, hours, days or months? I think "days" or "hours" would be good choices.
- Is there a need to show the age of individual issues/PRs as well?
- Should I separate the count of open PRs from issues while showing "Number of Open Issues" and the count of closed PRs at the time of displaying "Number of Closed Issues" for individual repositories?

_As per above discussion, I have understood that this project is about showing overall statistics for quick view, right? Hence showing ages of individual issues/PRs will not be required at this moment, will it be? Once the core features get completed, we can dive deeper into the details. What you all think?_

**Comment by scottgonzalez** [comment]
> What time unit should be used to show age, average age etc.?

That depends on the value. Use the most appropriate unit.

> Is there a need to show the age of individual issues/PRs as well?

No.

> Should I separate the count of open PRs from issues while showing "Number of Open Issues" and the count of closed PRs at the time of displaying "Number of Closed Issues" for individual repositories?

Yes, we should treat them as completely separate entities.

**Comment by gauravparmar** [comment]
@scottgonzalez :

> That depends on the value. Use the most appropriate unit.

You mean to say that I shall have to use multiple units depending on the value. e.g.- if the time is very short (let us say in seconds or minutes) then I should use small units (like - seconds or minutes) and if time is bigger (like some hours or days) then I should use a bigger time unit (like - hours or days) at that time because milliseconds or seconds would create a big number in that case. 
Is this what you said?

I shall have to decide range to switch among the time units as per the value.

**Comment by agcolom** [comment]
- units to show age: 
  - I'd go with days, as this is what is going to make sense when reviewing health of repos. 
- show the age of individual issues/PRs
  - I think it'd be good to show the age of the youngest and oldest in each repo graphically with the average also, to get easily spot repos with high and low activity.

@scottgonzalez Would that be ok with you?

**Comment by scottgonzalez** [comment]
> You mean to say that I shall have to use multiple units depending on the value.

Yes.

> I shall have to decide range to switch among the time units as per the value.

Just use an existing library like moment.js.

**Comment by scottgonzalez** [comment]
> I'd go with days, as this is what is going to make sense when reviewing health of repos.

Would you rather see something like "6 years, 50 days" or "2,050 days"? I'm ok if you really want to limit the max unit to days, but youngest could be something like "2 minutes" and I don't think you want to see "0 days" or even more strangely "0.0014 days."

> I think it'd be good to show the age of the youngest and oldest in each repo graphically with the average also, to get easily spot repos with high and low activity.

I don't think youngest and oldest will tell you anything about actual activity. You'll just see massively polarizing values in mature projects.

**Comment by agcolom** [comment]
> > I'd go with days, as this is what is going to make sense when reviewing health of repos.
> 
> Would you rather see something like "6 years, 50 days" or "2,050 days"? I'm ok if you really want to limit the max unit to days, but youngest could be something like "2 minutes" and I don't think you want to see "0 days" or even more strangely "0.0014 days."

sure, yes, seen that way your suggestion is the best one.

> > I think it'd be good to show the age of the youngest and oldest in each repo graphically with the average also, to get easily spot repos with high and low activity.
> 
> I don't think youngest and oldest will tell you anything about actual activity. You'll just see massively polarizing values in mature projects.

What I was thinking is that if your max age is 14months and min age is 12months, then nothing's been happening for 1 year and is looking stale. However, you could have another repo with a similar average where min age could be 7 days and max age could be 3 years. That tells us there are still old issues to be resolved but activity is still taking place.

**Comment by scottgonzalez** [comment]
Technically all that tells you is someone recently filed an issue.

If your youngest issue is 12 months old, there are a few likely scenarios:

1) Your project is dead. Nobody uses it anymore and therefore nobody files issues anymore.

2) Your project is officially complete and stable. People still use the project, but by its nature it no longer requires updates and no new bugs are being discovered.

3) Your project is still active, every new bug gets fixed relatively quickly, but there are some old, nasty bugs that you just can't seem to tackle.

You actually cannot differentiate between the first two cases purely by looking at issue activity. You can differentiate the third case by looking at other issue metrics.

**Comment by gauravparmar** [comment]
Yes. Now I also think that we can not stick to a particular time unit because it may result in some awkward number (like 0.003472222 days in case of 5 minutes).

**Comment by agcolom** [comment]
@scottgonzalez so would it be a good idea to also have an option to view other things such as latest PR/issue (whether closed or not)?

**Comment by scottgonzalez** [comment]
I'm not sure what value that would provide. You'll get much more insight into the project activity with a chart like http://bugs.jqueryui.com/ticketgraph.

**Comment by g31pranjal** [comment]
@scottgonzalez  @agcolom  : Can we display the recent activities on a particular repository in a **given frame of time** (say, 1 year, or rather, 1 month), apart from displaying overall activity ? 
This can serve two purposes : 
- This would kind of standardize the amount of activity in each repository i.e. Instead of looking at the entire data, a user just looks at the data of past 1 year. this will help in comparison.
- Moreover, displaying this data using chart like http://bugs.jqueryui.com/ticketgraph  (pointed out by @scottgonzalez ) will help to visualize any recent activity.

Can this solve the problem of comparison as well as health of a repository ?

**Comment by agcolom** [comment]
@g31pranjal it should be possible to select a timeframe. I think it'd be good to let the user do that either by selecting using a menu or graphically. Once we have all the data, this should not be a problem and charting libraries often offer this as default behavior.

**Comment by user5253** [comment]
@scottgonzalez , @agcolom , @arthurvr , @g31pranjal 
I also want to discuss a bit more on how to measure the <u>health of the repository</u>.
There are many factors which should be considered: <b>issues age range and avg. age, commit frequency, youngest issues and count, no. of watches, stars, forks made recently, etc. </b>(mentors please suggest more relevant factor).

Example: If your issue frequency is decreasing overtime and you are having a lots of stars and forks recently then your code quality is improving, and becoming less buggy and more useful.

Similarly for the examples given by @scottgonzalez <a href='https://github.com/jquery/content/issues/4#issuecomment-89415840'>above</a>

But my question is how to measure it and what weights should be given to each of the factor? Should we measure the health <i>relative to other repos</i> in Org. or also add some default manual values for each factor; or combine them both? And there are number of ways to analyse the same thing.

**Comment by agcolom** [comment]
@moizpalitanawala one way to measure health could also be that the number of opened issues is under a specific number (to be defined) and that we're closing more issues than we open. We could also defined various levels of 'health'

**Comment by user5253** [comment]
@agcolom, @scottgonzalez 
We are also planning to provide this as an opensource tool for other organisations too.. So will have to have a very flexible health measuring system. Stats which are great for one organisation might be below normal for others.
Other thing could be that we just keep "jquery org." needs in mind and release the tool and let them modify it according to their requirements. However this idea isn't appealing. The tool should just work if someone is using it!

**Comment by g31pranjal** [comment]
@agcolom  @moizpalitanawala 
Rather than defining 'health', wouldn't it be better to calculate and provide valuable insights about the repository based on the data we have in our hand, as was the [initial focus](https://github.com/jquery/content/issues/4#issuecomment-69899864), and draw conclusions based on a particular statistic ?? _as in Web Analytics, it does not tell the state of your website but, the parameters on which the site is measured and their inferences_

We can have 'health' feature, but since it is relative, it cannot be used to determine the current sate of a repository (even for repositories of jQuery org).
**eg.** 
take repo [jquery-ui](https://github.com/jquery/jquery-ui/pulls) : issues 0, Pull Rquests 1500+ (none opened in last 1 week) and [jquery](https://github.com/jquery/jquery/issues) : issues 350+, Pull Rquests 1700+ (2 issues & 7 PR opened last week), both have nearly equal activities but no correlation between their stats.

In this case it will be difficult to device a common method to calculate overall health.

**Comment by scottgonzalez** [comment]
Please stick with the scope that was already defined.

**Comment by gauravparmar** [comment]
A question that is coming to my mind again and again is that- 

"Why should we use a database when we have to update it by checking Github each time a user visits the Issue/PR Tracking System?"

I mean each time when the user visits the Issue/PR Tracking System then we shall have to compare the information available in our database with the information on Github so that the user sees updated information. I totally understand that there will be some fields for which values will not change but still to verify that we shall have to make a comparison that means in order to show updated information to a user, we shall have to make lots of comparisons between the information on Github and information available in our database each time a user visits the Issue/PR Tracking System. So is not it a kind of overhead? I mean if we have to fetch the information from Github each time then why to use a database? Can not we directly make use of the information fetched from Github since some of the information become obsolete after a period?

**Comment by scottgonzalez** [comment]
> I mean each time when the user visits the Issue/PR Tracking System then we shall have to compare the information available in our database with the information on Github so that the user sees updated information.

Absolutely not. We only care about what's in the database, which is updated on a regular basis.

> Can not we directly make use of the information fetched from Github since some of the information become obsolete after a period?

You would never be able to do any kind of in-depth analysis in a reasonable amount of time and probably without hitting the request limit without a database.

**Comment by gauravparmar** [comment]
@scottgonzalez : 
So the information presented to the user would come from the database which might have been updated some time before and hence it will not be a real time tracking as you said above in anwering someone else's question? 

Now I am again clear about the database concept. 

I totally agree with you on the matter that during analysis,  if the analysis is done using the database data then it can be done faster than the analysis done using data directly requested from Github since the latter would involve so many requests resulting in consumption of a lot of time to get the data and analyze it further.

**Comment by scottgonzalez** [comment]
> it will not be a real time tracking as you said above in anwering someone else's question?

Correct. See https://github.com/jquery/content/issues/4#issuecomment-83783181

Even if we had a full day delay between updates, the difference in actual stats would be negligible. Of course, we'll want to have more frequent updates than that, but the types of analysis mentioned above doesn't need real time tracking.

**Comment by g31pranjal** [comment]
I have tried to store the data from 20/44 jQuery repositories hosted on Github and it is sufficient to crawl and update the data at max once per day. It hardly takes 20 requests on an average to Github API to do this.

However, i was thinking of some kind of mechanism that can give preference to a more active repository (like jquery/jquery, jquery/jquery-mobile) to update more frequently than less active repositories. This can be done by finding mean activity rate (MAR) on a particular repository using the data we have, then frequency of updating a repository will be proportional to its MAR.

I was planning on this method. is it the right way we can do this ? @scottgonzalez @agcolom

**Comment by scottgonzalez** [comment]
> it is sufficient to crawl and update the data at max once per day

Sufficient for what? I'd say that's a minimum, not a maximum.

> However, i was thinking of some kind of mechanism that can give preference to a more active repository

Why? The time to find out that a repository has had no activity is less than a second and only costs one API call, right? I don't see how adding complexity helps here.

**Comment by g31pranjal** [comment]
@scottgonzalez 

> it is sufficient to crawl and update the data at max once per day
> 
> > Sufficient for what? I'd say that's a minimum, not a maximum.

yeah, its the minimum. i agree.

> Why? The time to find out that a repository has had no activity is less than a second and only costs one API call, right? I don't see how adding complexity helps here.
- I wanted to save upon the computation and recursive calls to the API. The "updated_at" for a repository gets updated even if there is a comment, change in description, wiki pages etc. Hence, there will be more frequent "trigger" to update, than we actually require (since we are interested in collecting only issues and pull requests).
- If there is update in around 20 of 44 repositories, fetching updates for each of the 20 repositories together may reach request limit. (since i will be tracking all the open issues & pr across all repos). 

now the question is, can we update our entire data at once without reaching request limits (considering there can be more repos in future..) ? if yes, then there is no need for adding complexity !!

**Comment by scottgonzalez** [comment]
> The "updated_at" for a repository gets updated even if there is a comment, change in description, wiki pages etc.

What "updated_at"? Why are you not just asking for all issues/PRs created after the last update time? See the `since` parameter in https://developer.github.com/v3/issues/#list-issues-for-a-repository.

**Comment by g31pranjal** [comment]
@scottgonzalez 
using `since` is an easy way to keep the issues updated. 

And then updating all the repos at once makes proper sense. I was actually looking for a way to avoid updating all the open issues every time. Thanks for the piece of advice...

another thing, we also need to keep track of the repositories currently on Github (so as to get info about any new repo being opened), does it makes sense to do this thing automatically or there will be some way to add a particular repository to track ?

**Comment by scottgonzalez** [comment]
To avoid multiple people building the same thing with different ideas, I'm just going to stop answering implementation questions until there's a single proper implementation to be discussing.

**Comment by agcolom** [comment]
@clarkbox FYI
